language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  # Install rustfmt
  - rustup component add rustfmt
  # Install clippy
  - if [ "$TRAVIS_OS_NAME" = linux ]; then rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu               ; fi
  - if [ "$TRAVIS_OS_NAME" = linux ]; then rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu; fi

script:
  # Check formatting
  - rustfmt --edition=2018 src/lib.rs --check
  # Run build and tests
  - cargo build --verbose --release
  - cargo test --verbose --release -- --nocapture
  # Generate documentation
  - cargo doc --verbose --release
  # Check clippy lints
  - if [ "$TRAVIS_OS_NAME" = linux ]; then cargo +nightly-2020-01-02 clippy; fi

notifications:
  email:
    on_success: change
    on_failure: always
