[package]
name = "str-macro"
description = "The str!() macro, similar to vec![] but for strings"
version = "0.1.0"
authors = ["Ammon Smith <ammon.i.smith@gmail.com>"]
edition = "2018"

[dependencies]
